import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { AuthProvider } from '@/context/AuthContext'
import { Inter , Latin } from 'next/font/google'
import Footer from '@/components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })
const latin = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={latin.className} id='light-mode'>
        <AuthProvider>
          <Navbar/>
            {children}
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  )
}
